-- สร้างตารางสำหรับเก็บข้อมูลกิจกรรมพนักงาน
CREATE TABLE IF NOT EXISTS employee_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name VARCHAR(255) NOT NULL,
    employee_id VARCHAR(50) NOT NULL,
    department VARCHAR(100) NOT NULL,
    activity_date DATE NOT NULL,
    activity_type VARCHAR(50) NOT NULL,
    activity_description TEXT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('normal', 'abnormal')),
    duration DECIMAL(5,2) NOT NULL CHECK (duration >= 0),
    abnormal_reason VARCHAR(50), -- เหตุผลที่สถานะไม่ปกติ
    abnormal_detail TEXT, -- รายละเอียดเพิ่มเติมเหตุผล
    shift VARCHAR(20), -- ข้อมูลกะการทำงาน
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- เพิ่ม constraints สำหรับประเภทกิจกรรม
    CONSTRAINT valid_activity_type CHECK (
        activity_type IN (
            'meeting', 'training', 'project', 'break', 
            'sick', 'personal', 'overtime', 'other', 'work'
        )
    ),
    
    -- เพิ่ม constraints สำหรับแผนก
    CONSTRAINT valid_department CHECK (
        department IN (
            'IT', 'HR', 'Finance', 'Marketing', 'Operations', 'Sales', 'MFG'
        )
    ),
    
    -- เพิ่ม constraints สำหรับเหตุผลที่ไม่ปกติ
    CONSTRAINT valid_abnormal_reason CHECK (
        abnormal_reason IS NULL OR abnormal_reason IN (
            'late', 'early_leave', 'absent', 'sick', 
            'personal_emergency', 'family_issue', 'transport_issue', 
            'equipment_failure', 'system_down', 'other'
        )
    ),
    
    -- เพิ่ม constraints สำหรับกะการทำงาน
    CONSTRAINT valid_shift CHECK (
        shift IS NULL OR shift IN (
            'กะ A', 'กะ B', 'กะ C', 'กะ D', 
            'Shift A', 'Shift B', 'Shift C', 'Shift D', 'Morning', 'Evening', 'Night'
        )
    )
);

-- สร้าง indexes สำหรับการค้นหาที่เร็วขึ้น
CREATE INDEX IF NOT EXISTS idx_employee_activities_employee_id ON employee_activities(employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_activities_date ON employee_activities(activity_date);
CREATE INDEX IF NOT EXISTS idx_employee_activities_department ON employee_activities(department);
CREATE INDEX IF NOT EXISTS idx_employee_activities_status ON employee_activities(status);

-- สร้าง RLS (Row Level Security) policies
ALTER TABLE employee_activities ENABLE ROW LEVEL SECURITY;

-- นโยบายสำหรับการอ่านข้อมูล (ทุกคนสามารถอ่านได้)
CREATE POLICY "Public read access" ON employee_activities
    FOR SELECT USING (true);

-- นโยบายสำหรับการเพิ่มข้อมูล (ทุกคนสามารถเพิ่มได้)
CREATE POLICY "Public insert access" ON employee_activities
    FOR INSERT WITH CHECK (true);

-- สร้าง view สำหรับแสดงสถิติพนักงาน
CREATE OR REPLACE VIEW employee_stats AS
SELECT 
    employee_id,
    employee_name,
    department,
    COUNT(*) as total_activities,
    SUM(CASE WHEN status = 'normal' THEN 1 ELSE 0 END) as normal_activities,
    SUM(CASE WHEN status = 'abnormal' THEN 1 ELSE 0 END) as abnormal_activities,
    SUM(duration) as total_hours,
    AVG(duration) as avg_duration,
    MIN(activity_date) as first_activity,
    MAX(activity_date) as last_activity
FROM employee_activities 
GROUP BY employee_id, employee_name, department
ORDER BY total_activities DESC;

-- สร้าง trigger function สำหรับ update timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.created_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- สร้าง trigger สำหรับตาราง employee_activities
CREATE TRIGGER update_employee_activities_created_at 
    BEFORE INSERT ON employee_activities 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- แทรกข้อมูลตัวอย่าง (optional)
INSERT INTO employee_activities (
    employee_name, employee_id, department, activity_date, 
    activity_type, activity_description, status, duration,
    abnormal_reason, abnormal_detail, shift
) VALUES 
    ('สมชาย ใจดี', 'C25XXX', 'IT', '2024-01-15', 'meeting', 'ประชุมโปรเจคใหม่', 'normal', 2, NULL, NULL, NULL),
    ('สมศรี รักดี', 'C25XXX', 'HR', '2024-01-15', 'training', 'อบรมทักษะการสื่อสาร', 'normal', 4, NULL, NULL, NULL),
    ('สมศรี รักดี', 'C25XXX', 'HR', '2024-01-16', 'sick', 'มีไข้และปวดหัว', 'abnormal', 8, 'sick', 'มีไข้สูง 38.5 องศา จึงต้องพักผ่อน', NULL),
    ('วิชัย รุ่งเรือง', 'C25XXX', 'Finance', '2024-01-17', 'project', 'ทำงานโปรเจคงบประมาณ', 'normal', 6, NULL, NULL, NULL),
    ('มานี มีสุข', 'C25XXX', 'Marketing', '2024-01-18', 'overtime', 'ทำงานล่วงเวลา Campaign', 'normal', 3, NULL, NULL, NULL),
    ('สมคิด รักเรียน', 'C25XXX', 'IT', '2024-01-19', 'project', 'ทำงานโปรเจค', 'abnormal', 4, 'late', 'รถติดหนักมาก ติดอยู่ 2 ชั่วโมง', NULL),
    ('สมหญิง มั่งคั่ง', 'C25XXX', 'Sales', '2024-01-20', 'meeting', 'ประชุมลูกค้า', 'abnormal', 2, 'early_leave', 'ลูกเสี้ยวป่วยฉุกเฉินต้องรีบกลับ', NULL),
    ('สมศักดิ์ เจริญ', 'C25XXX', 'Operations', '2024-01-21', 'break', 'พักผ่อน', 'abnormal', 8, 'equipment_failure', 'คอมพิวเตอร์ใช้งานไม่ได้เฉยๆ เสียหาย', NULL),
    -- ข้อมูลตัวอย่างพนักงานกะ A MFG
    ('สมศักดิ์ รักงาน', 'C25XXX', 'MFG', '2024-01-22', 'work', 'ปฏิบัติงานตามปกติ', 'normal', 8, NULL, NULL, 'กะ A'),
    ('สมศรี สุขใจ', 'C25XXX', 'MFG', '2024-01-22', 'work', 'ปฏิบัติงานตามปกติ', 'normal', 8, NULL, NULL, 'กะ A'),
    ('วิชัย เจริญ', 'C25XXX', 'MFG', '2024-01-22', 'work', 'ปฏิบัติงานตามปกติ', 'abnormal', 7.5, 'late', 'รถติดหนักมาก มาสาย 30 นาที', 'กะ A');